Dictionary = {
    "Kuta":"Dog",
    "Bili":"Cat",
    "Tota":"Parrot",
    "Serr":"Lion",
    "Garibo":"Poor",
    "Ameer":"Rich",
    "Swagat": "Welcome",
    "Pyar": "Love",
    "Dhanyavaad": "Thank you",
    "Namaste": "Hello",
    "Safalta": "Success",
    "Khushi": "Happiness",
    "Shanti": "Peace",
    "Jeevan": "Life",
    "Samvaad": "Communication",
    "Samay": "Time",
    "Sajha": "Share",
    "Aasha": "Hope",
    "Swasthya": "Health",
    "Shiksha": "Education",
    "Samriddhi": "Prosperity",
    "Samarthan": "Support",
    "Samjhauta": "Compromise",
    "Samarpan": "Dedication",
    "Anand": "Joy",
    "Vishwas": "Trust",
    "Vikas": "Development",
    "Sanyam": "Discipline",
    "Sneh": "Affection",
    "Safalta": "Achievement",
    "Vishwas": "Belief",
    "Shakti": "Power",
    "Vishram": "Rest",
    "Sangharsh": "Struggle"
}
Update_Dictionary_1 = {
    'Namaste': 'Hello',
    'Dhanyavaad': 'Thank you',
    'Haan': 'Yes',
    'Nahi': 'No',
    'Kripaya': 'Please',
    'Maaf kijiye': 'Excuse me',
    'Kahan': 'Where',
    'Kab': 'When',
    'Kaise': 'How',
    'Kyun': 'Why',
    'Vyakti': 'Person',
    'Samay': 'Time',
    'Din': 'Day',
    'Hafte': 'Week',
    'Mahina': 'Month',
    'Saal': 'Year',
    'Accha': 'Good',
    'Bura': 'Bad',
    'Bada': 'Big',
    'Chota': 'Small',
    'Sach': 'Truth',
    'Jhooth': 'Lie',
    'Beech': 'Middle',
    'Bahar': 'Outside',
    'Andar': 'Inside',
    'Saath': 'Together',
    'Alag': 'Separate',
    'Kareeb': 'Near',
    'Door': 'Far',
    'Desh': 'Country',
    'Shehar': 'City',
    'Punjikrit': 'Registered',
    'Safalta': 'Success',
    'Asafalta': 'Failure',
    'Shuruat': 'Beginning',
    'Samapti': 'End',
    'Sankhya': 'Number',
    'Ganit': 'Mathematics',
    'Vigyan': 'Science',
    'Itihas': 'History',
    'Bhugol': 'Geography',
    'Rang': 'Color',
    'Bhasha': 'Language',
    'Samvidhan': 'Constitution',
    'Samajh': 'Understanding',
    'Vishwas': 'Belief',
    'Dharm': 'Religion',
    'Sanskriti': 'Culture',
    'Seva': 'Service',
    'Swasthya': 'Health',
    'Shiksha': 'Education',
    'Safal': 'Successful',
    'Nirasha': 'Disappointment',
    'Khushi': 'Happiness',
    'Dukh': 'Sadness',
    'Asha': 'Hope',
    'Bhay': 'Fear',
    'Khatra': 'Danger',
    'Suraksha': 'Safety',
    'Band': 'Closed',
    'Khula': 'Open',
    'Khareedari': 'Shopping',
    'Khana': 'Food',
    'Paani': 'Water',
    'Hawa': 'Air',
    'Aag': 'Fire',
    'Dharti': 'Earth',
    'Station': 'Station',
    'Aspatal': 'Hospital',
    'Bazaar': 'Market',
    'Bagicha': 'Garden',
    'School': 'School',
    'College': 'College',
    'Vishwavidyalaya': 'University',
    'Sadak': 'Road',
    'Pul': 'Bridge',
    'Ghar': 'House',
    'Building': 'Building',
    'Kam': 'Work',
    'Adhyayan': 'Study',
    'Khel': 'Game',
    'Khel ka maidan': 'Playground',
    'Samudra': 'Sea',
    'Nadi': 'River',
    'Jheel': 'Lake',
    'Pahadi': 'Mountain',
    'Jangal': 'Forest',
    'Janwar': 'Animal',
    'Pakshi': 'Bird',
    'Keet': 'Insect',
    'Phool': 'Flower',
    'Ped': 'Tree',
    'Dhwaj': 'Flag',
    'Sikka': 'Coin',
    'Note': 'Note',
    'Patra': 'Letter',
    'Kitab': 'Book',
    'Kagaz': 'Paper',
    'Chitthi': 'Envelope',
    'Barish': 'Rain',
    'Barf': 'Snow',
    'Bijli': 'Electricity',
    'Aandhi': 'Storm',
    'Toofan': 'Hurricane',
    'Bijli girna': 'Blackout',
    'Dhoop': 'Sunlight',
    'Chand': 'Moon',
    'Tara': 'Star',
    'Badal': 'Cloud',
    'Aakash': 'Sky',
    'Sooraj': 'Sun',
    'Sitara': 'Planet',
    'Grah': 'Astronomical Body',
    'Nritya': 'Dance',
    'Sangeet': 'Music',
    'Kavita': 'Poem',
    'Lekh': 'Article',
    'Natak': 'Play',
    'Film': 'Movie',
    'Painting': 'Painting',
    'Sulekh': 'Drawing',
    'Photography': 'Photography'
}
Update_Dictionary_2 = {
    'Pakode': 'Fritters',
    'Chai': 'Tea',
    'Coffe': 'Coffee',
    'Roti': 'Roti',
    'Sabzi': 'Vegetables',
    'Chawal': 'Rice',
    'Dal': 'Lentils',
    'Paneer': 'Paneer',
    'Samosa': 'Samosa',
    'Pani Puri': 'Pani Puri',
    'Pav Bhaji': 'Pav Bhaji',
    'Golgappa': 'Golgappa',
    'Poha': 'Poha',
    'Idli': 'Idli',
    'Dosa': 'Dosa',
    'Biryani': 'Biryani',
    'Vada': 'Vada',
    'Raita': 'Raita',
    'Lassi': 'Lassi',
    'Jalebi': 'Jalebi',
    'Gajar Halwa': 'Carrot Halwa',
    'Gulab Jamun': 'Gulab Jamun',
    'Rasgulla': 'Rasgulla',
    'Barfi': 'Barfi',
    'Rajma': 'Kidney Beans',
    'Chole': 'Chickpeas',
    'Bhature': 'Bhature',
    'Ghee': 'Clarified Butter',
    'Chutney': 'Chutney',
    'Laddu': 'Laddu',
    'Srikhand': 'Srikhand',
    'Papad': 'Papad',
    'Thali': 'Thali',
    'Aloo': 'Potato',
    'Gobi': 'Cauliflower',
    'Pyaz': 'Onion',
    'Tamatar': 'Tomato',
    'Hari Mirchi':'Green Chili'
}

Dictionary.update(Update_Dictionary_1)
Dictionary.update(Update_Dictionary_2)


print (Dictionary.keys())

a = input("Enter the Hindi Word From the above keys:\n")
found = Dictionary.get(a)
if (found is None ):
    print ("Ahh Sorry there is no word in my Dictionary you have provided :( ")
else :
    print ('Your translated word in english is:',found)
