Unique = set({})
a1 = int(input ("Enter your unique number 1:"))
Unique.add(a1)
a2 = int(input ("Enter your unique number 2:"))
Unique.add(a2)
a3 = int(input ("Enter your unique number 3:"))
Unique.add(a3)
a4 = int(input ("Enter your unique number 4:"))
Unique.add(a4)
a5 = int(input ("Enter your unique number 5:"))
Unique.add(a5)
a6 = int(input ("Enter your unique number 6:"))
Unique.add(a6)
a7 = int(input ("Enter your unique number 7:"))
Unique.add(a7)
a8 = int(input ("Enter your unique number 8:"))
Unique.add(a8)

print(Unique)